#ifndef ULTREALITY_RENDERING_D3D12_COM_INTERFACE_H
#define ULTREALITY_RENDERING_D3D12_COM_INTERFACE_H

namespace UltReality::Rendering::D3D12
{

}

#endif // !ULTREALITY_RENDERING_D3D12_COM_INTERFACE_H
